name: Build Python Baseimage with libgit2

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_libgit2
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
            prefix=libgit2-
            suffix=
      - name: Build and push for many architectures
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.libgit2
          push: ${{ github.event_name != 'pull_request' }}
          platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta_libgit2.outputs.tags }}
          labels: ${{ steps.meta_libgit2.outputs.labels }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_pygit2
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
            prefix=pygit2-
            suffix=
      - name: Build and push for many architectures
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.pygit2
          push: ${{ github.event_name != 'pull_request' }}
          platforms: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta_pygit2.outputs.tags }}
          labels: ${{ steps.meta_pygit2.outputs.labels }}
